/* Warning: auto-generated file! Regenerate with 'pnpm build' in 'tools/' folder. */
import type {GPUType} from './GPUType'

/** Auto-generated file */
/* eslint-disable @typescript-eslint/no-misused-new */
/* eslint-disable @typescript-eslint/no-unused-vars */

type pointer<T = any> = number
type int8 = number
type uint8 = number
type int16 = number
type uint16 = number
type int32 = number
type uint32 = number
type int64 = number
type uint64 = number
type float = number
type double = number

declare const getTypeSymbol: symbol

// see UniformBindType in sculptcore\source\gpu\shader.h
enum UniformBindType {
  FLOAT = 0,
  DOUBLE = 1,
  BYTE = 2,
  UBYTE = 3,
  SHORT = 4,
  USHORT = 5,
  INT = 6,
  UINT = 7,
  FLOAT2 = 8,
  FLOAT3 = 9,
  FLOAT4 = 10,
  INT2 = 11,
  INT3 = 12,
  INT4 = 13,
  UINT2 = 14,
  UINT3 = 15,
  UINT4 = 16,
  DOUBLE2 = 17,
  DOUBLE3 = 18,
  DOUBLE4 = 19,
  SHORT2 = 20,
  SHORT3 = 21,
  SHORT4 = 22,
  USHORT2 = 23,
  USHORT3 = 24,
  USHORT4 = 25,
  BYTE2 = 26,
  BYTE3 = 27,
  BYTE4 = 28,
  UBYTE2 = 29,
  UBYTE3 = 30,
  UBYTE4 = 31
}

// we want to generate this helper type so type disambiguoution/inference 
// works keyed on the [getTypeSymbol] property
type UniformBindTypeMap = {
  [UniformBindType.FLOAT]: number
  [UniformBindType.FLOAT2]: [number, number]
  [UniformBindType.FLOAT3]: [number, number, number]
  [UniformBindType.FLOAT4]: [number, number, number, number]
  //... other types from UniformBindType
}

export interface UniformDef<T, K extends keyof UniformBindTypeMap> {
  [Symbol.dispose](): void
  // getTypeSymbol will have to be defined somewhere we can import it from,
  // perhaps in a (generated) file next to the root generated index.ts
  [getTypeSymbol]: K

  name: string
  type: GPUType
  elemSize: int32

  // defaultValue would normally be mapped to T, but we want it to be
  // mapped to this helper generated by the binding union system.
  // we could perhaps add a 'disambiguator' litestl::binding::types::Enum* property 
  // to ParentTemplateParam that can be used by the typescript generator code.
  defaultValue: UniformBindTypeMap[K]
}

declare const test1: UniformDef<float, UniformBindType.FLOAT>
declare const test2: UniformDef<float, UniformBindType.FLOAT2>

// type of defaultValue is number
test1.defaultValue

// type of defaultValue is [number, number]
test2.defaultValue

