packages:
  - tests
  - source/litestl/binding/typescriptRuntime
  - tools
  - source/litestl/tests
  - typescript
  - tests/testViewer3D

ignoredBuiltDependencies:
  - electron
  - esbuild

onlyBuiltDependencies:
  - unrs-resolver
