macro(test file extra_lib)
set(target "${file}_out")
add_executable(${target} "${file}")
target_link_libraries(${target} util ${extra_lib} math)
target_include_directories(${target} PUBLIC util)
target_include_directories(${target} PUBLIC math)
target_include_directories(${target} PUBLIC mesh)
target_include_directories(${target} PUBLIC binding_generators)
target_include_directories(${target} PUBLIC binding)
add_test(NAME ${target} COMMAND ${target})
endmacro()

test(test_mesh.cc "mesh")
test(test_delaunay.cc "mesh")
test(test_edge_collapse.cc "mesh")
test(test_props.cc "props")
test(test_meshlog_topo.cc "meshlog;mesh;spatial")
test(test_brush.cc "")
test(test_binding.cc "binding_generators")
test(test_debug_script.cc "debug_core")
#test(test_constexpr_bug.cc "")
