#include "emit_registry.h"

#include <cctype>
#include <string>

/** Registry emitter for extra (out-of-repo) kernels — see the "Extra kernel
 * dirs" section in documentation/brush_compute.md. Emits the enum-item .inc
 * included by Binder<SculptBrushes>::bind() plus the factory-dispatch header
 * consumed by brushes/extra.h. Ids are positional (SculptBrushesBuiltinCount +
 * index, in --in order) — per-build only, nothing persists them. */

namespace sculptcore::brush::sbrush {

namespace {

string upperCopy(const string &s)
{
  string out;
  for (const char *p = s.c_str(); *p; p++) {
    out += (char)std::toupper((unsigned char)*p);
  }
  return out;
}

bool equalNoCase(const string &a, const string &b)
{
  const char *pa = a.c_str(), *pb = b.c_str();
  for (; *pa && *pb; pa++, pb++) {
    if (std::toupper((unsigned char)*pa) != std::toupper((unsigned char)*pb)) {
      return false;
    }
  }
  return *pa == *pb;
}

bool isIdentifier(const string &s)
{
  const char *p = s.c_str();
  if (!*p || (!std::isalpha((unsigned char)*p) && *p != '_')) {
    return false;
  }
  for (p++; *p; p++) {
    if (!std::isalnum((unsigned char)*p) && *p != '_') {
      return false;
    }
  }
  return true;
}

string itoa(int v)
{
  return string(std::to_string(v).c_str());
}

} // namespace

RegistryResult emitRegistry(const Vector<RegistryEntry> &extras,
                            const Vector<string> &builtinStems,
                            const Vector<string> &builtinAttrNames,
                            const Vector<string> &reserved)
{
  RegistryResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  for (int i = 0; i < (int)extras.size(); i++) {
    const RegistryEntry &e = extras[i];
    string enumName = upperCopy(e.attrName);

    if (!isIdentifier(enumName)) {
      err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
          "\" does not uppercase to a valid enum identifier");
    }
    for (const auto &bs : builtinStems) {
      if (e.stem == bs) {
        err(string("extra brush '") + e.stem +
            "' collides with a built-in kernel of the same file stem (" + bs +
            ".sbrush): the generated include <stem>.brush.gen.h would be ambiguous");
      }
    }
    for (const auto &bn : builtinAttrNames) {
      if (e.attrName == bn) {
        err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
            "\" duplicates a built-in brush name");
      }
    }
    for (const auto &rn : reserved) {
      if (equalNoCase(enumName, rn)) {
        err(string("extra brush '") + e.stem + "': enum item \"" + enumName +
            "\" collides with reserved built-in enum item \"" + rn + "\"");
      }
    }
    for (int j = i + 1; j < (int)extras.size(); j++) {
      if (e.stem == extras[j].stem) {
        err(string("duplicate extra kernel stem '") + e.stem +
            "' (same filename in two extra kernel dirs?)");
      }
      if (e.attrName == extras[j].attrName) {
        err(string("duplicate @brush name \"") + e.attrName + "\" in extras '" + e.stem +
            "' and '" + extras[j].stem + "'");
      }
      if (equalNoCase(enumName, upperCopy(extras[j].attrName))) {
        err(string("extras '") + e.stem + "' and '" + extras[j].stem +
            "' map to the same enum item \"" + enumName + "\" (case-insensitive)");
      }
    }
  }

  if (r.errors.size() > 0) {
    return r;
  }

  const char *banner = "// AUTO-GENERATED by sbrushc --registry — DO NOT EDIT.\n";

  string &inc = r.enumInc;
  inc += banner;
  inc += "// Included inside litestl::binding::Binder<SculptBrushes>::bind()\n";
  inc += "// (brushes/types.h) when SCULPTCORE_EXTRA_BRUSHES is defined.\n";
  for (int i = 0; i < (int)extras.size(); i++) {
    inc += string("e->addItem(\"") + upperCopy(extras[i].attrName) +
           "\", sculptcore::brush::SculptBrushesBuiltinCount + " + itoa(i) + ");\n";
  }

  string &h = r.genHeader;
  h += banner;
  h += "// Extra-kernel registry: factory dispatch + metadata for kernels compiled\n";
  h += "// from SCULPTCORE_EXTRA_KERNEL_DIRS. Consumed via brushes/extra.h; the\n";
  h += "// matching enum items live in sculptcore_extra_brushes_enum.inc.\n";
  h += "#pragma once\n";
  h += "#include \"brush/brush_command.h\"\n";
  h += "#include \"brush/brushes/types.h\"\n";
  bool anyNeighbor = false;
  for (const auto &e : extras) {
    anyNeighbor = anyNeighbor || e.usesNeighbor;
  }
  if (anyNeighbor) {
    h += "#include \"brush/neighbor_source.h\"\n";
  }
  for (const auto &e : extras) {
    h += string("#include \"") + e.stem + ".brush.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int extraBrushCount = ") + itoa((int)extras.size()) + ";\n\n";
  h += "inline bool extraBrushUsesForNeighbor(int id)\n{\n";
  if (anyNeighbor) {
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      if (extras[i].usesNeighbor) {
        h += string("  case ") + itoa(i) + ": // " + extras[i].stem + "\n";
        h += "    return true;\n";
      }
    }
    h += "  default:\n    return false;\n  }\n";
  } else {
    h += "  (void)id;\n  return false;\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "/** Dispatch an extra-brush id to its generated factory. Returns false when\n";
  h += " * `id` is not an extra brush (the caller falls through to its own error\n";
  h += " * path). for_neighbor kernels select CsrNbr/LiveDiskNbr like SMOOTH. */\n";
  h += "template <CommandTypes TYPES, sculptcore::brush::AccumMode AccMode>\n";
  h += "inline bool createExtraBrush(int id, bool csrNeighbors,\n";
  h += "                             BrushCommandDef<CommandCtx<TYPES>> &def)\n";
  h += "{\n";
  if (!anyNeighbor) {
    h += "  (void)csrNeighbors;\n";
  }
  if (extras.size() == 0) {
    h += "  (void)id;\n  (void)def;\n  return false;\n";
  } else {
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      const RegistryEntry &e = extras[i];
      h += string("  case ") + itoa(i) + ": // " + e.stem + "\n";
      if (e.usesNeighbor) {
        h += "    if (csrNeighbors) {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::CsrNbr, AccMode>(def);\n";
        h += "    } else {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::LiveDiskNbr, AccMode>(def);\n";
        h += "    }\n";
      } else {
        h += string("    create") + e.cppName + "Brush<TYPES, AccMode>(def);\n";
      }
      h += "    return true;\n";
    }
    h += "  default:\n    return false;\n  }\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush::command\n";

  return r;
}

} // namespace sculptcore::brush::sbrush
