#include "emit_registry.h"

#include "emit_wgsl.h"

#include <cctype>
#include <string>

/** Registry emitter for extra (out-of-repo) kernels — see the "Extra kernel
 * dirs" section in documentation/brush_compute.md. Emits the enum-item .inc
 * included by Binder<SculptBrushes>::bind() plus the factory-dispatch header
 * consumed by brushes/extra.h. Ids are positional (SculptBrushesBuiltinCount +
 * index, in --in order) — per-build only, nothing persists them. */

namespace sculptcore::brush::sbrush {

namespace {

string upperCopy(const string &s)
{
  string out;
  for (const char *p = s.c_str(); *p; p++) {
    out += (char)std::toupper((unsigned char)*p);
  }
  return out;
}

bool equalNoCase(const string &a, const string &b)
{
  const char *pa = a.c_str(), *pb = b.c_str();
  for (; *pa && *pb; pa++, pb++) {
    if (std::toupper((unsigned char)*pa) != std::toupper((unsigned char)*pb)) {
      return false;
    }
  }
  return *pa == *pb;
}

bool isIdentifier(const string &s)
{
  const char *p = s.c_str();
  if (!*p || (!std::isalpha((unsigned char)*p) && *p != '_')) {
    return false;
  }
  for (p++; *p; p++) {
    if (!std::isalnum((unsigned char)*p) && *p != '_') {
      return false;
    }
  }
  return true;
}

string itoa(int v)
{
  return string(std::to_string(v).c_str());
}

string floatLit(double v)
{
  char buf[64];
  std::snprintf(buf, sizeof(buf), "%.17g", v);
  bool hasDot = false;
  for (const char *p = buf; *p; p++) {
    if (*p == '.' || *p == 'e' || *p == 'E') {
      hasDot = true;
      break;
    }
  }
  string s(buf);
  if (!hasDot) {
    s += ".0";
  }
  s += "f";
  return s;
}

// First character uppercased — matches the cpp emitter's tex<Cap>Eval naming.
string capCopy(const string &s)
{
  string out = s;
  if (out.size() > 0) {
    out[0] = (char)std::toupper((unsigned char)out[0]);
  }
  return out;
}

// Identifier-safe, capitalized unit stem for the tex<Unit>UnitWgsl symbol.
string unitSymbol(const string &stem)
{
  string out;
  for (const char *p = stem.c_str(); *p; p++) {
    out += std::isalnum((unsigned char)*p) ? *p : '_';
  }
  return capCopy(out);
}

} // namespace

EmitResult emitTextureUnitHeader(TextureUnit &unit, const string &stem)
{
  Brush scratch;
  scratch.sourceFile = unit.sourceFile;
  for (auto &td : unit.textures) {
    // `imported` puts the SB_TEX_DEF_ guard around each definition, so the
    // unit header can coexist in a TU with brush headers that pulled the
    // same texture via `use texture`.
    td.imported = true;
    scratch.textures.append(std::move(td));
  }

  EmitResult cppR = emitCppTextureDefs(scratch);
  EmitResult wgslR = emitWgslTextureDefs(scratch);
  EmitResult r;
  for (const auto &e : cppR.errors) {
    r.errors.append(e);
  }
  for (const auto &e : wgslR.errors) {
    r.errors.append(e);
  }
  if (r.errors.size() > 0) {
    return r;
  }

  string &h = r.text;
  h += "// AUTO-GENERATED by sbrushc --texture-unit — DO NOT EDIT.\n";
  h += string("// Source: ") + scratch.sourceFile + "\n";
  h += "#pragma once\n";
  h += "#include \"brush/texture_eval.h\"\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "using litestl::math::float3;\n\n";
  h += cppR.text;
  h += "// WGSL module text for this unit's textures (the T5 shader splice).\n";
  h += string("static const char tex") + unitSymbol(stem) + "UnitWgsl[] = R\"__sbtex__(\n";
  h += wgslR.text;
  h += ")__sbtex__\";\n\n";
  h += "} // namespace sculptcore::brush::command\n";
  return r;
}

EmitResult emitTextureRegistry(const Vector<string> &stems,
                               const Vector<const TextureUnit *> &units)
{
  EmitResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  for (int i = 0; i < (int)units.size(); i++) {
    for (int j = i + 1; j < (int)units.size(); j++) {
      if (stems[i] == stems[j]) {
        err(string("duplicate texture-unit stem '") + stems[i] +
            "' (same filename in two kernel dirs?)");
      }
    }
  }
  for (int i = 0; i < (int)units.size(); i++) {
    for (const auto &td : units[i]->textures) {
      for (int j = 0; j < (int)units.size(); j++) {
        for (const auto &other : units[j]->textures) {
          bool same = (j == i) ? (&other > &td) : (j > i);
          if (same && td.name == other.name) {
            err(string("texture '") + td.name + "' defined in both '" + stems[i] +
                ".stex' and '" + stems[j] + ".stex'");
          }
        }
      }
    }
  }
  if (r.errors.size() > 0) {
    return r;
  }

  int count = 0;
  for (const auto *u : units) {
    count += (int)u->textures.size();
  }

  string &h = r.text;
  h += "// AUTO-GENERATED by sbrushc --texture-registry — DO NOT EDIT.\n";
  h += "// One row per precompiled standalone texture; consumed by\n";
  h += "// brush/texture_registry.cc.\n";
  h += "#pragma once\n";
  h += "#include \"brush/texture_registry.h\"\n";
  for (const auto &s : stems) {
    h += string("#include \"") + s + ".tex.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += string("inline constexpr int kTextureRegistryCount = ") + itoa(count) + ";\n";
  if (count == 0) {
    h += "static const ::sculptcore::brush::TextureRegistryEntry *kTextureRegistry = "
         "nullptr;\n";
  } else {
    h += string("static const ::sculptcore::brush::TextureRegistryEntry kTextureRegistry[") +
         itoa(count) + "] = {\n";
    for (int i = 0; i < (int)units.size(); i++) {
      for (const auto &td : units[i]->textures) {
        string cap = capCopy(td.name);
        int nParams = 0;
        for (const auto &tp : td.texParams) {
          nParams += tp.isConst ? 0 : 1;
        }
        h += string("    {\"") + td.name + "\", &tex" + cap + "Eval, ";
        h += (td.slabSize > 0) ? (string("tex") + cap + "ParamDefaults") : string("nullptr");
        h += string(", ") + itoa(td.slabSize) + ", ";
        h += (nParams > 0) ? (string("tex") + cap + "ParamManifest") : string("nullptr");
        h += string(", ") + itoa(nParams) + ", tex" + unitSymbol(stems[i]) + "UnitWgsl, " +
             (td.usesMap ? "true" : "false") + "},\n";
      }
    }
    h += "};\n";
  }
  h += "\n} // namespace sculptcore::brush::command\n";
  return r;
}

RegistryResult emitRegistry(const Vector<RegistryEntry> &extras,
                            const Vector<string> &builtinStems,
                            const Vector<string> &builtinAttrNames,
                            const Vector<string> &reserved)
{
  RegistryResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  for (int i = 0; i < (int)extras.size(); i++) {
    const RegistryEntry &e = extras[i];
    string enumName = upperCopy(e.attrName);

    if (!isIdentifier(enumName)) {
      err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
          "\" does not uppercase to a valid enum identifier");
    }
    for (const auto &bs : builtinStems) {
      if (e.stem == bs) {
        err(string("extra brush '") + e.stem +
            "' collides with a built-in kernel of the same file stem (" + bs +
            ".sbrush): the generated include <stem>.brush.gen.h would be ambiguous");
      }
    }
    for (const auto &bn : builtinAttrNames) {
      if (e.attrName == bn) {
        err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
            "\" duplicates a built-in brush name");
      }
    }
    for (const auto &rn : reserved) {
      if (equalNoCase(enumName, rn)) {
        err(string("extra brush '") + e.stem + "': enum item \"" + enumName +
            "\" collides with reserved built-in enum item \"" + rn + "\"");
      }
    }
    for (int j = i + 1; j < (int)extras.size(); j++) {
      if (e.stem == extras[j].stem) {
        err(string("duplicate extra kernel stem '") + e.stem +
            "' (same filename in two extra kernel dirs?)");
      }
      if (e.attrName == extras[j].attrName) {
        err(string("duplicate @brush name \"") + e.attrName + "\" in extras '" + e.stem +
            "' and '" + extras[j].stem + "'");
      }
      if (equalNoCase(enumName, upperCopy(extras[j].attrName))) {
        err(string("extras '") + e.stem + "' and '" + extras[j].stem +
            "' map to the same enum item \"" + enumName + "\" (case-insensitive)");
      }
    }
  }

  // Named-float store slots: dedupe store uniforms by name across all extras
  // (first-appearance order → dense per-build indices). Two kernels sharing a
  // name share the slot, so their DSL defaults must agree.
  Vector<StoreUniform> slots;
  for (const auto &e : extras) {
    for (const auto &su : e.storeUniforms) {
      bool found = false;
      for (const auto &s : slots) {
        if (s.name == su.name) {
          found = true;
          if (s.def != su.def) {
            err(string("store uniform \"") + su.name + "\" is declared with conflicting "
                "defaults in two extra kernels (shared name = shared slot; align the "
                "`= <n>` defaults or rename one)");
          }
          break;
        }
      }
      if (!found) {
        slots.append(su);
      }
    }
  }

  if (r.errors.size() > 0) {
    return r;
  }

  const char *banner = "// AUTO-GENERATED by sbrushc --registry — DO NOT EDIT.\n";

  string &inc = r.enumInc;
  inc += banner;
  inc += "// Included inside litestl::binding::Binder<SculptBrushes>::bind()\n";
  inc += "// (brushes/types.h) when SCULPTCORE_EXTRA_BRUSHES is defined.\n";
  for (int i = 0; i < (int)extras.size(); i++) {
    inc += string("e->addItem(\"") + upperCopy(extras[i].attrName) +
           "\", sculptcore::brush::SculptBrushesBuiltinCount + " + itoa(i) + ");\n";
  }

  string &h = r.genHeader;
  h += banner;
  h += "// Extra-kernel registry: factory dispatch + metadata for kernels compiled\n";
  h += "// from SCULPTCORE_EXTRA_KERNEL_DIRS. Consumed via brushes/extra.h; the\n";
  h += "// matching enum items live in sculptcore_extra_brushes_enum.inc.\n";
  h += "#pragma once\n";
  h += "#include \"brush/brush_command.h\"\n";
  h += "#include \"brush/brushes/types.h\"\n";
  bool anyNeighbor = false;
  for (const auto &e : extras) {
    anyNeighbor = anyNeighbor || e.usesNeighbor;
  }
  if (anyNeighbor) {
    h += "#include \"brush/neighbor_source.h\"\n";
  }
  h += "\n";
  // Named-float store slots — declared before the kernel includes because the
  // kernel templates reference kExtraSlot_<name> as a non-dependent name.
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int extraNamedFloatCount = ") + itoa((int)slots.size()) +
       ";\n";
  for (int i = 0; i < (int)slots.size(); i++) {
    h += string("inline constexpr int kExtraSlot_") + slots[i].name + " = " + itoa(i) +
         ";\n";
  }
  if (slots.size() > 0) {
    h += string("inline constexpr float kExtraNamedFloatDefaults[") +
         itoa((int)slots.size()) + "] = {";
    for (int i = 0; i < (int)slots.size(); i++) {
      if (i) {
        h += ", ";
      }
      h += floatLit(slots[i].def);
    }
    h += "};\n";
  }
  h += "\n";
  h += "/** Size the store and seed DSL defaults for the tail being grown —\n";
  h += " * already-present slots are never rewritten, so values set before the\n";
  h += " * first command creation (setNamedFloat) survive. */\n";
  h += "inline void ensureExtraUniformDefaults(Brush &b)\n{\n";
  if (slots.size() > 0) {
    h += "  int old = (int)b.namedFloats.size();\n";
    h += "  if (old >= extraNamedFloatCount) {\n    return;\n  }\n";
    h += "  while ((int)b.namedFloats.size() < extraNamedFloatCount) {\n";
    h += "    b.namedFloats.append(0.0f);\n  }\n";
    h += "  for (int i = old; i < extraNamedFloatCount; i++) {\n";
    h += "    b.namedFloats[i] = kExtraNamedFloatDefaults[i];\n  }\n";
  } else {
    h += "  (void)b;\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush\n\n";
  for (const auto &e : extras) {
    h += string("#include \"") + e.stem + ".brush.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int extraBrushCount = ") + itoa((int)extras.size()) + ";\n\n";
  h += "inline bool extraBrushUsesForNeighbor(int id)\n{\n";
  if (anyNeighbor) {
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      if (extras[i].usesNeighbor) {
        h += string("  case ") + itoa(i) + ": // " + extras[i].stem + "\n";
        h += "    return true;\n";
      }
    }
    h += "  default:\n    return false;\n  }\n";
  } else {
    h += "  (void)id;\n  return false;\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "/** Dispatch an extra-brush id to its generated factory. Returns false when\n";
  h += " * `id` is not an extra brush (the caller falls through to its own error\n";
  h += " * path). for_neighbor kernels select CsrNbr/LiveDiskNbr like SMOOTH; the\n";
  h += " * named-float store is sized + default-seeded per command creation. */\n";
  h += "template <CommandTypes TYPES, sculptcore::brush::AccumMode AccMode>\n";
  h += "inline bool createExtraBrush(int id, bool csrNeighbors, sculptcore::brush::Brush &brush,\n";
  h += "                             BrushCommandDef<CommandCtx<TYPES>> &def)\n";
  h += "{\n";
  if (!anyNeighbor) {
    h += "  (void)csrNeighbors;\n";
  }
  if (extras.size() == 0) {
    h += "  (void)id;\n  (void)brush;\n  (void)def;\n  return false;\n";
  } else {
    h += "  ensureExtraUniformDefaults(brush);\n";
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      const RegistryEntry &e = extras[i];
      h += string("  case ") + itoa(i) + ": // " + e.stem + "\n";
      if (e.usesNeighbor) {
        h += "    if (csrNeighbors) {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::CsrNbr, AccMode>(def);\n";
        h += "    } else {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::LiveDiskNbr, AccMode>(def);\n";
        h += "    }\n";
      } else {
        h += string("    create") + e.cppName + "Brush<TYPES, AccMode>(def);\n";
      }
      h += "    return true;\n";
    }
    h += "  default:\n    return false;\n  }\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush::command\n";

  return r;
}

} // namespace sculptcore::brush::sbrush
