#include "emit_registry.h"

#include "emit_wgsl.h"

#include <cctype>
#include <string>

/** Registry emitter for extra (out-of-repo) kernels — see the "Extra kernel
 * dirs" section in documentation/brush_compute.md. Emits the enum-item .inc
 * included by Binder<SculptBrushes>::bind() plus the factory-dispatch header
 * consumed by brushes/extra.h. Ids are positional (SculptBrushesBuiltinCount +
 * index, in --in order) — per-build only, nothing persists them. */

namespace sculptcore::brush::sbrush {

namespace {

string upperCopy(const string &s)
{
  string out;
  for (const char *p = s.c_str(); *p; p++) {
    out += (char)std::toupper((unsigned char)*p);
  }
  return out;
}

bool equalNoCase(const string &a, const string &b)
{
  const char *pa = a.c_str(), *pb = b.c_str();
  for (; *pa && *pb; pa++, pb++) {
    if (std::toupper((unsigned char)*pa) != std::toupper((unsigned char)*pb)) {
      return false;
    }
  }
  return *pa == *pb;
}

bool isIdentifier(const string &s)
{
  const char *p = s.c_str();
  if (!*p || (!std::isalpha((unsigned char)*p) && *p != '_')) {
    return false;
  }
  for (p++; *p; p++) {
    if (!std::isalnum((unsigned char)*p) && *p != '_') {
      return false;
    }
  }
  return true;
}

string itoa(int v)
{
  return string(std::to_string(v).c_str());
}

string floatLit(double v)
{
  char buf[64];
  std::snprintf(buf, sizeof(buf), "%.17g", v);
  bool hasDot = false;
  for (const char *p = buf; *p; p++) {
    if (*p == '.' || *p == 'e' || *p == 'E') {
      hasDot = true;
      break;
    }
  }
  string s(buf);
  if (!hasDot) {
    s += ".0";
  }
  s += "f";
  return s;
}

// First character uppercased — matches the cpp emitter's tex<Cap>Eval naming.
string capCopy(const string &s)
{
  string out = s;
  if (out.size() > 0) {
    out[0] = (char)std::toupper((unsigned char)out[0]);
  }
  return out;
}

// Identifier-safe, capitalized unit stem for the tex<Unit>UnitWgsl symbol.
string unitSymbol(const string &stem)
{
  string out;
  for (const char *p = stem.c_str(); *p; p++) {
    out += std::isalnum((unsigned char)*p) ? *p : '_';
  }
  return capCopy(out);
}

} // namespace

EmitResult emitTextureUnitHeader(TextureUnit &unit, const string &stem)
{
  Brush scratch;
  scratch.sourceFile = unit.sourceFile;
  for (auto &td : unit.textures) {
    // `imported` puts the SB_TEX_DEF_ guard around each definition, so the
    // unit header can coexist in a TU with brush headers that pulled the
    // same texture via `use texture`.
    td.imported = true;
    scratch.textures.append(std::move(td));
  }

  EmitResult cppR = emitCppTextureDefs(scratch);
  EmitResult wgslR = emitWgslTextureDefs(scratch);
  EmitResult r;
  for (const auto &e : cppR.errors) {
    r.errors.append(e);
  }
  for (const auto &e : wgslR.errors) {
    r.errors.append(e);
  }
  if (r.errors.size() > 0) {
    return r;
  }

  string &h = r.text;
  h += "// AUTO-GENERATED by sbrushc --texture-unit — DO NOT EDIT.\n";
  h += string("// Source: ") + scratch.sourceFile + "\n";
  h += "#pragma once\n";
  h += "#include \"brush/texture_eval.h\"\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "using litestl::math::float3;\n\n";
  h += cppR.text;
  h += "// WGSL module text for this unit's textures (the T5 shader splice).\n";
  h += string("static const char tex") + unitSymbol(stem) + "UnitWgsl[] = R\"__sbtex__(\n";
  h += wgslR.text;
  h += ")__sbtex__\";\n\n";
  h += "} // namespace sculptcore::brush::command\n";
  return r;
}

EmitResult emitTextureRegistry(const Vector<string> &stems,
                               const Vector<const TextureUnit *> &units)
{
  EmitResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  for (int i = 0; i < (int)units.size(); i++) {
    for (int j = i + 1; j < (int)units.size(); j++) {
      if (stems[i] == stems[j]) {
        err(string("duplicate texture-unit stem '") + stems[i] +
            "' (same filename in two kernel dirs?)");
      }
    }
  }
  for (int i = 0; i < (int)units.size(); i++) {
    for (const auto &td : units[i]->textures) {
      for (int j = 0; j < (int)units.size(); j++) {
        for (const auto &other : units[j]->textures) {
          bool same = (j == i) ? (&other > &td) : (j > i);
          if (same && td.name == other.name) {
            err(string("texture '") + td.name + "' defined in both '" + stems[i] +
                ".stex' and '" + stems[j] + ".stex'");
          }
        }
      }
    }
  }
  if (r.errors.size() > 0) {
    return r;
  }

  int count = 0;
  for (const auto *u : units) {
    count += (int)u->textures.size();
  }

  string &h = r.text;
  h += "// AUTO-GENERATED by sbrushc --texture-registry — DO NOT EDIT.\n";
  h += "// One row per precompiled standalone texture; consumed by\n";
  h += "// brush/texture_registry.cc.\n";
  h += "#pragma once\n";
  h += "#include \"brush/texture_registry.h\"\n";
  for (const auto &s : stems) {
    h += string("#include \"") + s + ".tex.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += string("inline constexpr int kTextureRegistryCount = ") + itoa(count) + ";\n";
  if (count == 0) {
    h += "static const ::sculptcore::brush::TextureRegistryEntry *kTextureRegistry = "
         "nullptr;\n";
  } else {
    h += string("static const ::sculptcore::brush::TextureRegistryEntry kTextureRegistry[") +
         itoa(count) + "] = {\n";
    for (int i = 0; i < (int)units.size(); i++) {
      for (const auto &td : units[i]->textures) {
        string cap = capCopy(td.name);
        int nParams = 0;
        for (const auto &tp : td.texParams) {
          nParams += tp.isConst ? 0 : 1;
        }
        h += string("    {\"") + td.name + "\", &tex" + cap + "Eval, ";
        h += (td.slabSize > 0) ? (string("tex") + cap + "ParamDefaults") : string("nullptr");
        h += string(", ") + itoa(td.slabSize) + ", ";
        h += (nParams > 0) ? (string("tex") + cap + "ParamManifest") : string("nullptr");
        h += string(", ") + itoa(nParams) + ", tex" + unitSymbol(stems[i]) + "UnitWgsl, " +
             (td.usesMap ? "true" : "false") + "},\n";
      }
    }
    h += "};\n";
  }
  h += "\n} // namespace sculptcore::brush::command\n";
  return r;
}

BuiltinRegistryResult emitBuiltinRegistry(const Vector<BuiltinEntry> &kernels,
                                          const Vector<string> &toolIds)
{
  BuiltinRegistryResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  // Pair each id with the kernel claiming it. A name claimed twice or not at all
  // is an error: the dispatcher would otherwise silently lose a tool, and the
  // enum item would bind to an id nothing implements.
  Vector<int> owner;
  for (int i = 0; i < (int)toolIds.size(); i++) {
    if (!isIdentifier(toolIds[i])) {
      err(string("tool id table: \"") + toolIds[i] + "\" is not a valid enum identifier");
    }
    for (int j = i + 1; j < (int)toolIds.size(); j++) {
      if (toolIds[i] == toolIds[j]) {
        err(string("tool id table: duplicate name \"") + toolIds[i] + "\"");
      }
    }
    owner.append(-1);
  }

  for (int k = 0; k < (int)kernels.size(); k++) {
    for (const auto &t : kernels[k].tools) {
      int id = -1;
      for (int i = 0; i < (int)toolIds.size(); i++) {
        if (toolIds[i] == t) {
          id = i;
          break;
        }
      }
      if (id < 0) {
        err(string("kernel '") + kernels[k].stem + "': @tool " + t +
            " is not in the id table (brushes/tools.txt)");
        continue;
      }
      if (owner[id] >= 0) {
        err(string("tool ") + t + " is claimed by both '" + kernels[owner[id]].stem +
            "' and '" + kernels[k].stem + "'");
        continue;
      }
      owner[id] = k;
    }
  }
  for (int i = 0; i < (int)toolIds.size(); i++) {
    if (owner[i] < 0) {
      err(string("tool ") + toolIds[i] +
          " is in the id table but no kernel declares `@tool " + toolIds[i] + "`");
    }
  }

  if (r.errors.size() > 0) {
    return r;
  }

  const char *banner = "// AUTO-GENERATED by sbrushc --builtin-registry — DO NOT EDIT.\n";

  string &inc = r.enumInc;
  inc += banner;
  inc += "// Included inside litestl::binding::Binder<SculptBrushes>::bind()\n";
  inc += "// (brushes/types.h). Order and ids come from brushes/tools.txt; the enum\n";
  inc += "// items themselves are hand-written there.\n";
  for (int i = 0; i < (int)toolIds.size(); i++) {
    inc += string("e->addItem(\"") + toolIds[i] + "\", SculptBrushes::" + toolIds[i] + ");\n";
  }

  // Kernels serving no tool are compiled (their .gen.h is checked in) but take
  // no id — leave them out rather than emitting an unreachable include.
  Vector<int> used;
  for (int i = 0; i < (int)toolIds.size(); i++) {
    bool seen = false;
    for (int u : used) {
      seen = seen || u == owner[i];
    }
    if (!seen) {
      used.append(owner[i]);
    }
  }

  bool anyNeighbor = false;
  for (int u : used) {
    anyNeighbor = anyNeighbor || kernels[u].usesNeighbor;
  }

  string &h = r.genHeader;
  h += banner;
  h += "// Built-in brush registry: which kernel each SculptBrushes id dispatches to,\n";
  h += "// plus the per-kernel topology facts the executor keys stroke setup on.\n";
  h += "// Regenerate with `node make.mjs codegen`; inputs are the kernels' @tool /\n";
  h += "// @fulltopo annotations and brushes/tools.txt.\n";
  h += "#pragma once\n";
  h += "#include \"brush/brush_command.h\"\n";
  if (anyNeighbor) {
    h += "#include \"brush/neighbor_source.h\"\n";
  }
  for (int u : used) {
    h += string("#include \"brush/kernels/generated/") + kernels[u].stem + ".brush.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int builtinBrushCount = ") + itoa((int)toolIds.size()) + ";\n\n";
  h += "/** Enum item name per id — the reflected names, without a BindingManager. */\n";
  h += string("inline constexpr const char *kBuiltinBrushNames[") +
       itoa((int)toolIds.size()) + "] = {\n";
  for (int i = 0; i < (int)toolIds.size(); i++) {
    h += string("    \"") + toolIds[i] + "\",\n";
  }
  h += "};\n\n";
  h += "/** The kernel's .sbrush stem, for diagnostics and roster tests. */\n";
  h += string("inline constexpr const char *kBuiltinBrushKernels[") +
       itoa((int)toolIds.size()) + "] = {\n";
  for (int i = 0; i < (int)toolIds.size(); i++) {
    h += string("    \"") + kernels[owner[i]].stem + "\",\n";
  }
  h += "};\n\n";
  h += "/** True when the kernel has a `for_neighbor` loop, i.e. it is instantiated\n";
  h += " * against a neighbor source and reads neighbors during the dab. */\n";
  h += "inline bool builtinBrushUsesForNeighbor(int id)\n{\n";
  h += "  switch (id) {\n";
  for (int i = 0; i < (int)toolIds.size(); i++) {
    if (kernels[owner[i]].usesNeighbor) {
      h += string("  case ") + itoa(i) + ": // " + toolIds[i] + "\n";
    }
  }
  if (anyNeighbor) {
    h += "    return true;\n";
  }
  h += "  default:\n    return false;\n  }\n";
  h += "}\n\n";
  h += "/** `@fulltopo`: the kernel or its host pre-pass walks live topology links\n";
  h += " * every dab, so the stroke must not freeze topology. */\n";
  h += "inline bool builtinBrushFullTopo(int id)\n{\n";
  h += "  switch (id) {\n";
  bool anyFullTopo = false;
  for (int i = 0; i < (int)toolIds.size(); i++) {
    if (kernels[owner[i]].fullTopo) {
      h += string("  case ") + itoa(i) + ": // " + toolIds[i] + "\n";
      anyFullTopo = true;
    }
  }
  if (anyFullTopo) {
    h += "    return true;\n";
  }
  h += "  default:\n    return false;\n  }\n";
  h += "}\n\n";
  h += "/** The kernel has a `face` stage, so it is dispatched per face and reaches\n";
  h += " * its verts through the live face loop. */\n";
  h += "inline bool builtinBrushFaceMode(int id)\n{\n";
  h += "  switch (id) {\n";
  bool anyFaceStage = false;
  for (int i = 0; i < (int)toolIds.size(); i++) {
    if (kernels[owner[i]].faceStage) {
      h += string("  case ") + itoa(i) + ": // " + toolIds[i] + "\n";
      anyFaceStage = true;
    }
  }
  if (anyFaceStage) {
    h += "    return true;\n";
  }
  h += "  default:\n    return false;\n  }\n";
  h += "}\n\n";
  h += "} // namespace sculptcore::brush\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "/** Dispatch a built-in brush id to its generated factory. Returns false when\n";
  h += " * `id` is not a built-in (the caller falls through to the extras registry).\n";
  h += " * The two neighbor sources are template parameters, not literals: the mesh\n";
  h += " * executor passes CsrNbr/LiveDiskNbr, the grid executor its own GridCsrNbr.\n";
  h += " * A @fulltopo kernel always takes NbrLive — its pre-pass thaws topology, so\n";
  h += " * a stroke-start CSR snapshot would go stale under it. */\n";
  h += "template <CommandTypes TYPES,\n";
  h += "          sculptcore::brush::NbrSource NbrCsr,\n";
  h += "          sculptcore::brush::NbrSource NbrLive,\n";
  h += "          sculptcore::brush::AccumMode AccMode>\n";
  h += "inline bool createBuiltinBrush(int id, bool csrNeighbors,\n";
  h += "                               BrushCommandDef<CommandCtx<TYPES>> &def)\n";
  h += "{\n";
  if (!anyNeighbor) {
    h += "  (void)csrNeighbors;\n";
  }
  h += "  switch (id) {\n";
  for (int u : used) {
    const BuiltinEntry &e = kernels[u];
    for (int i = 0; i < (int)toolIds.size(); i++) {
      if (owner[i] == u) {
        h += string("  case ") + itoa(i) + ": // " + toolIds[i] + "\n";
      }
    }
    string factory = string("create") + capCopy(e.stem) + "Brush<TYPES, ";
    if (!e.usesNeighbor) {
      h += string("    ") + factory + "AccMode>(def);\n";
    } else if (e.fullTopo) {
      h += string("    ") + factory + "NbrLive, AccMode>(def);\n";
    } else {
      h += "    if (csrNeighbors) {\n";
      h += string("      ") + factory + "NbrCsr, AccMode>(def);\n";
      h += "    } else {\n";
      h += string("      ") + factory + "NbrLive, AccMode>(def);\n";
      h += "    }\n";
    }
    h += "    return true;\n";
  }
  h += "  default:\n    return false;\n  }\n";
  h += "}\n\n";
  h += "} // namespace sculptcore::brush::command\n";

  return r;
}

RegistryResult emitRegistry(const Vector<RegistryEntry> &extras,
                            const Vector<string> &builtinStems,
                            const Vector<string> &builtinAttrNames,
                            const Vector<string> &reserved)
{
  RegistryResult r;
  auto err = [&r](const string &msg) { r.errors.append(msg); };

  for (int i = 0; i < (int)extras.size(); i++) {
    const RegistryEntry &e = extras[i];
    string enumName = upperCopy(e.attrName);

    if (!isIdentifier(enumName)) {
      err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
          "\" does not uppercase to a valid enum identifier");
    }
    for (const auto &bs : builtinStems) {
      if (e.stem == bs) {
        err(string("extra brush '") + e.stem +
            "' collides with a built-in kernel of the same file stem (" + bs +
            ".sbrush): the generated include <stem>.brush.gen.h would be ambiguous");
      }
    }
    for (const auto &bn : builtinAttrNames) {
      if (e.attrName == bn) {
        err(string("extra brush '") + e.stem + "': @brush name \"" + e.attrName +
            "\" duplicates a built-in brush name");
      }
    }
    for (const auto &rn : reserved) {
      if (equalNoCase(enumName, rn)) {
        err(string("extra brush '") + e.stem + "': enum item \"" + enumName +
            "\" collides with reserved built-in enum item \"" + rn + "\"");
      }
    }
    for (int j = i + 1; j < (int)extras.size(); j++) {
      if (e.stem == extras[j].stem) {
        err(string("duplicate extra kernel stem '") + e.stem +
            "' (same filename in two extra kernel dirs?)");
      }
      if (e.attrName == extras[j].attrName) {
        err(string("duplicate @brush name \"") + e.attrName + "\" in extras '" + e.stem +
            "' and '" + extras[j].stem + "'");
      }
      if (equalNoCase(enumName, upperCopy(extras[j].attrName))) {
        err(string("extras '") + e.stem + "' and '" + extras[j].stem +
            "' map to the same enum item \"" + enumName + "\" (case-insensitive)");
      }
    }
  }

  // Named-float store slots: dedupe store uniforms by name across all extras
  // (first-appearance order → dense per-build indices). Two kernels sharing a
  // name share the slot, so their DSL defaults must agree.
  Vector<StoreUniform> slots;
  for (const auto &e : extras) {
    for (const auto &su : e.storeUniforms) {
      bool found = false;
      for (const auto &s : slots) {
        if (s.name == su.name) {
          found = true;
          if (s.def != su.def) {
            err(string("store uniform \"") + su.name + "\" is declared with conflicting "
                "defaults in two extra kernels (shared name = shared slot; align the "
                "`= <n>` defaults or rename one)");
          }
          break;
        }
      }
      if (!found) {
        slots.append(su);
      }
    }
  }

  if (r.errors.size() > 0) {
    return r;
  }

  const char *banner = "// AUTO-GENERATED by sbrushc --registry — DO NOT EDIT.\n";

  string &inc = r.enumInc;
  inc += banner;
  inc += "// Included inside litestl::binding::Binder<SculptBrushes>::bind()\n";
  inc += "// (brushes/types.h) when SCULPTCORE_EXTRA_BRUSHES is defined.\n";
  for (int i = 0; i < (int)extras.size(); i++) {
    inc += string("e->addItem(\"") + upperCopy(extras[i].attrName) +
           "\", sculptcore::brush::SculptBrushesBuiltinCount + " + itoa(i) + ");\n";
  }

  string &h = r.genHeader;
  h += banner;
  h += "// Extra-kernel registry: factory dispatch + metadata for kernels compiled\n";
  h += "// from SCULPTCORE_EXTRA_KERNEL_DIRS. Consumed via brushes/extra.h; the\n";
  h += "// matching enum items live in sculptcore_extra_brushes_enum.inc.\n";
  h += "#pragma once\n";
  h += "#include \"brush/brush_command.h\"\n";
  h += "#include \"brush/brushes/types.h\"\n";
  bool anyNeighbor = false;
  for (const auto &e : extras) {
    anyNeighbor = anyNeighbor || e.usesNeighbor;
  }
  if (anyNeighbor) {
    h += "#include \"brush/neighbor_source.h\"\n";
  }
  h += "\n";
  // Named-float store slots — declared before the kernel includes because the
  // kernel templates reference kExtraSlot_<name> as a non-dependent name.
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int extraNamedFloatCount = ") + itoa((int)slots.size()) +
       ";\n";
  for (int i = 0; i < (int)slots.size(); i++) {
    h += string("inline constexpr int kExtraSlot_") + slots[i].name + " = " + itoa(i) +
         ";\n";
  }
  if (slots.size() > 0) {
    h += string("inline constexpr float kExtraNamedFloatDefaults[") +
         itoa((int)slots.size()) + "] = {";
    for (int i = 0; i < (int)slots.size(); i++) {
      if (i) {
        h += ", ";
      }
      h += floatLit(slots[i].def);
    }
    h += "};\n";
  }
  h += "\n";
  h += "/** Size the store and seed DSL defaults for the tail being grown —\n";
  h += " * already-present slots are never rewritten, so values set before the\n";
  h += " * first command creation (setNamedFloat) survive. */\n";
  h += "inline void ensureExtraUniformDefaults(Brush &b)\n{\n";
  if (slots.size() > 0) {
    h += "  int old = (int)b.namedFloats.size();\n";
    h += "  if (old >= extraNamedFloatCount) {\n    return;\n  }\n";
    h += "  while ((int)b.namedFloats.size() < extraNamedFloatCount) {\n";
    h += "    b.namedFloats.append(0.0f);\n  }\n";
    h += "  for (int i = old; i < extraNamedFloatCount; i++) {\n";
    h += "    b.namedFloats[i] = kExtraNamedFloatDefaults[i];\n  }\n";
  } else {
    h += "  (void)b;\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush\n\n";
  for (const auto &e : extras) {
    h += string("#include \"") + e.stem + ".brush.gen.h\"\n";
  }
  h += "\n";
  h += "namespace sculptcore::brush {\n\n";
  h += string("inline constexpr int extraBrushCount = ") + itoa((int)extras.size()) + ";\n\n";
  h += "inline bool extraBrushUsesForNeighbor(int id)\n{\n";
  if (anyNeighbor) {
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      if (extras[i].usesNeighbor) {
        h += string("  case ") + itoa(i) + ": // " + extras[i].stem + "\n";
        h += "    return true;\n";
      }
    }
    h += "  default:\n    return false;\n  }\n";
  } else {
    h += "  (void)id;\n  return false;\n";
  }
  h += "}\n\n";
  // The two topology facts the executor keys stroke setup on, for extras too:
  // an out-of-repo kernel that walks live links must not be given a
  // topology-frozen stroke, and nothing else in the host knows it does.
  {
    struct Pred {
      const char *fn;
      const char *doc;
      bool RegistryEntry::*member;
    };
    const Pred preds[] = {
        {"extraBrushFullTopo",
         "/** `@fulltopo`: the kernel or its host pre-pass walks live topology links\n"
         " * every dab, so the stroke must not freeze topology. */\n",
         &RegistryEntry::fullTopo},
        {"extraBrushFaceMode",
         "/** The kernel has a `face` stage, so it is dispatched per face and reaches\n"
         " * its verts through the live face loop. */\n",
         &RegistryEntry::faceStage},
    };
    for (const Pred &p : preds) {
      bool any = false;
      for (int i = 0; i < (int)extras.size(); i++) {
        if (extras[i].*(p.member)) {
          any = true;
        }
      }
      h += p.doc;
      h += string("inline bool ") + p.fn + "(int id)\n{\n";
      if (any) {
        h += "  switch (id - SculptBrushesBuiltinCount) {\n";
        for (int i = 0; i < (int)extras.size(); i++) {
          if (extras[i].*(p.member)) {
            h += string("  case ") + itoa(i) + ": // " + extras[i].stem + "\n";
            h += "    return true;\n";
          }
        }
        h += "  default:\n    return false;\n  }\n";
      } else {
        h += "  (void)id;\n  return false;\n";
      }
      h += "}\n\n";
    }
  }
  h += "} // namespace sculptcore::brush\n\n";
  h += "namespace sculptcore::brush::command {\n\n";
  h += "/** Dispatch an extra-brush id to its generated factory. Returns false when\n";
  h += " * `id` is not an extra brush (the caller falls through to its own error\n";
  h += " * path). for_neighbor kernels select CsrNbr/LiveDiskNbr like SMOOTH; the\n";
  h += " * named-float store is sized + default-seeded per command creation. */\n";
  h += "template <CommandTypes TYPES, sculptcore::brush::AccumMode AccMode>\n";
  h += "inline bool createExtraBrush(int id, bool csrNeighbors, sculptcore::brush::Brush &brush,\n";
  h += "                             BrushCommandDef<CommandCtx<TYPES>> &def)\n";
  h += "{\n";
  if (!anyNeighbor) {
    h += "  (void)csrNeighbors;\n";
  }
  if (extras.size() == 0) {
    h += "  (void)id;\n  (void)brush;\n  (void)def;\n  return false;\n";
  } else {
    h += "  ensureExtraUniformDefaults(brush);\n";
    h += "  switch (id - SculptBrushesBuiltinCount) {\n";
    for (int i = 0; i < (int)extras.size(); i++) {
      const RegistryEntry &e = extras[i];
      h += string("  case ") + itoa(i) + ": // " + e.stem + "\n";
      if (e.usesNeighbor && e.fullTopo) {
        // @fulltopo: its pre-pass thaws topology, so a stroke-start CSR snapshot
        // would go stale under it — same rule as the built-ins.
        h += string("    create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::LiveDiskNbr, AccMode>(def);\n";
      } else if (e.usesNeighbor) {
        h += "    if (csrNeighbors) {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::CsrNbr, AccMode>(def);\n";
        h += "    } else {\n";
        h += string("      create") + e.cppName +
             "Brush<TYPES, sculptcore::brush::LiveDiskNbr, AccMode>(def);\n";
        h += "    }\n";
      } else {
        h += string("    create") + e.cppName + "Brush<TYPES, AccMode>(def);\n";
      }
      h += "    return true;\n";
    }
    h += "  default:\n    return false;\n  }\n";
  }
  h += "}\n\n";
  h += "} // namespace sculptcore::brush::command\n";

  return r;
}

} // namespace sculptcore::brush::sbrush
