/** Emit::run — the generated kernel header, top to bottom. */

#include "emit_cpp_internal.h"

namespace sculptcore::brush::sbrush::cpp_emit {

void Emit::run()
{
  string lowerName =
      lower(string(brush->attrName.size() > 0 ? brush->attrName : brush->cppName));
  string camelName = kernelCppName(brush->attrName, brush->cppName);

  // for_neighbor brushes are templated on a NbrSource policy (live disk walk
  // vs cached CSR), chosen once at brush-command creation. Detect it up front
  // so the includes and function signatures can be emitted accordingly.
  const bool usesNbr = brushUsesNeighbor();

  write("// AUTO-GENERATED by sbrushc — DO NOT EDIT.\n");
  write("// Source: ");
  write(brush->sourceFile);
  write("\n");
  write("#pragma once\n");
  write("#include <cstring>\n");
  write("#include \"brush/brush_command.h\"\n");
  write("#include \"brush/capture_policy.h\"\n");
  write("#include \"spatial/spatial_enums.h\"\n");
  write("#include \"mesh/mesh_iter.h\"\n");
  if (brush->textures.size() > 0)
    write("#include \"brush/texture_eval.h\"\n");
  if (usesNbr)
    write("#include \"brush/neighbor_source.h\"\n");
  write("\n");
  write("namespace sculptcore::brush::command {\n\n");

  // Struct decls — at namespace scope so reduce/vertex functions can
  // both name them. Skip if the brush declared none.
  for (const auto &sd : brush->structs) {
    write("struct ");
    write(sd.name);
    write(" {\n");
    for (const auto &f : sd.fields) {
      write("  ");
      write(typeKindName(f.type));
      write(" ");
      write(f.name);
      write(";\n");
    }
    write("};\n\n");
  }

  // Forward-mode dual prelude — emitted before bodies so the inlined grad()
  // rewrite resolves. A scalar dual is (v, ∂v); a float3 dual carries a 3-col
  // Jacobian. Overloads + sbd_* chain rules drive the rewrite in emitDual.
  if (brushUsesGrad()) {
    // Guarded like SB_TEX_DEF_: two grad brushes aggregated into one TU
    // (brushes/all.h) must not redefine the prelude.
    write("#ifndef SB_DUAL_PRELUDE\n#define SB_DUAL_PRELUDE\n");
    write("struct sbdual { float v; float3 d; };\n");
    write("struct sbdual3 { float3 v; float3 dx, dy, dz; };\n");
    write("inline sbdual sb_c(float x){return {x,float3(0,0,0)};}\n");
    write("inline sbdual3 sb_c3(float3 p){return "
          "{p,float3(0,0,0),float3(0,0,0),float3(0,0,0)};}\n");
    write("inline sbdual3 sb_seed3(float3 p){return "
          "{p,float3(1,0,0),float3(0,1,0),float3(0,0,1)};}\n");
    write("inline sbdual sb_comp(sbdual3 a,int i){return "
          "{a.v[i],float3(a.dx[i],a.dy[i],a.dz[i])};}\n");
    write("inline sbdual3 sb_v3(sbdual x,sbdual y,sbdual z){return "
          "{float3(x.v,y.v,z.v),float3(x.d[0],y.d[0],z.d[0]),float3(x.d[1],y.d[1],z.d["
          "1]),float3(x.d[2],y.d[2],z.d[2])};}\n");
    write("inline sbdual operator+(sbdual a,sbdual b){return {a.v+b.v,a.d+b.d};}\n");
    write("inline sbdual operator-(sbdual a,sbdual b){return {a.v-b.v,a.d-b.d};}\n");
    // litestl float3 has no unary minus, only the component-wise binaries.
    write("inline sbdual operator-(sbdual a){return {-a.v,a.d*-1.0f};}\n");
    write("inline sbdual operator*(sbdual a,sbdual b){return "
          "{a.v*b.v,a.d*b.v+b.d*a.v};}\n");
    write("inline sbdual operator/(sbdual a,sbdual b){return "
          "{a.v/b.v,(a.d*b.v-b.d*a.v)/(b.v*b.v)};}\n");
    write(
        "inline sbdual sbd_sin(sbdual a){return {std::sin(a.v),a.d*std::cos(a.v)};}\n");
    write("inline sbdual sbd_cos(sbdual a){return "
          "{std::cos(a.v),a.d*(-std::sin(a.v))};}\n");
    write("inline sbdual sbd_sqrt(sbdual a){float r=std::sqrt(a.v);return "
          "{r,a.d*(r>0?0.5f/r:0.0f)};}\n");
    write("inline sbdual sbd_abs(sbdual a){return "
          "{std::abs(a.v),a.d*(a.v<0?-1.0f:1.0f)};}\n");
    write("inline sbdual sbd_dot(sbdual3 a,sbdual3 b){return "
          "{a.v.dot(b.v),a.dx*b.v[0]+b.dx*a.v[0]+a.dy*b.v[1]+b.dy*a.v[1]+a.dz*b.v[2]+b."
          "dz*a.v[2]};}\n");
    write("inline sbdual sbd_length(sbdual3 a){return sbd_sqrt(sbd_dot(a,a));}\n");
    write("inline sbdual sbd_mix(sbdual a,sbdual b,sbdual t){return a+(b-a)*t;}\n");
    write("inline sbdual sbd_floor(sbdual a){return "
          "{std::floor(a.v),float3(0,0,0)};}\n");
    write("inline sbdual sbd_fract(sbdual a){return {a.v-std::floor(a.v),a.d};}\n");
    write("#endif  // SB_DUAL_PRELUDE\n\n");
    if (brush->textures.size() > 0 && anyTextureUsesMap()) {
      // Exact quotient-rule dual of texMapPoint: q = M*(p,1), value r.v
      // mirrors texMapPoint's arithmetic bitwise; each Jacobian column runs
      // c through M's linear part with the same divisor-clamp mask g.
      write("#ifndef SB_DUAL_MAPPOINT\n#define SB_DUAL_MAPPOINT\n");
      write("inline float3 sbd_mapCol(const float *m, float3 c, float3 q, float d, "
            "float g){\n");
      write("  float qx = m[0]*c[0] + m[1]*c[1] + m[2]*c[2];\n");
      write("  float qy = m[4]*c[0] + m[5]*c[1] + m[6]*c[2];\n");
      write("  float qz = m[8]*c[0] + m[9]*c[1] + m[10]*c[2];\n");
      write("  float qw = (m[12]*c[0] + m[13]*c[1] + m[14]*c[2]) * g;\n");
      write("  return float3((qx*d - q[0]*qw)/(d*d), (qy*d - q[1]*qw)/(d*d), "
            "(qz*d - q[2]*qw)/(d*d));\n");
      write("}\n");
      write("inline sbdual3 sbd_mapPoint(const TexEvalCtx *ctx, sbdual3 p){\n");
      write("  if (!ctx) { return p; }\n");
      write("  const float *m = ctx->map_matrix;\n");
      write("  float x = m[0]*p.v[0] + m[1]*p.v[1] + m[2]*p.v[2] + m[3];\n");
      write("  float y = m[4]*p.v[0] + m[5]*p.v[1] + m[6]*p.v[2] + m[7];\n");
      write("  float z = m[8]*p.v[0] + m[9]*p.v[1] + m[10]*p.v[2] + m[11];\n");
      write("  float w = m[12]*p.v[0] + m[13]*p.v[1] + m[14]*p.v[2] + m[15];\n");
      write("  float g = std::abs(w) > 1e-6f ? 1.0f : 0.0f;\n");
      write("  float d = g > 0.0f ? w : 1.0f;\n");
      write("  float3 q = float3(x, y, z);\n");
      write("  sbdual3 r;\n");
      write("  r.v = float3(x / d, y / d, z / d);\n");
      write("  r.dx = sbd_mapCol(m, p.dx, q, d, g);\n");
      write("  r.dy = sbd_mapCol(m, p.dy, q, d, g);\n");
      write("  r.dz = sbd_mapCol(m, p.dz, q, d, g);\n");
      write("  return r;\n");
      write("}\n");
      write("#endif  // SB_DUAL_MAPPOINT\n\n");
    }
  }

  // Texture eval functions (inline + `use texture` imports) — pure, at
  // namespace scope so the vertex/reduce bodies can call them. Each is
  // preceded by its param-defaults slab when it declares runtime params.
  for (const auto &td : brush->textures) {
    emitTextureBlock(td);
  }

  // pre-stage: AttrSaver-gated undo capture, driven by the brush's `save` set.
  emitPreStage(lowerName);

  // Host stages — CPU-only setup that runs before any per-node work
  // for a dab. Emitted first so reduce/vertex (which may read ctx
  // fields the host populated) can rely on its side effects.
  Vector<const Stage *> hostStages;
  for (const auto &st : brush->stages) {
    if (st.kind == StageKind::Host)
      hostStages.append(&st);
  }
  for (const auto *st : hostStages) {
    emitHostStage(*st, lowerName);
  }

  // Reduce stages — emitted before the vertex stage so the vertex
  // function can call them by name.
  Vector<const Stage *> reduceStages;
  for (const auto &st : brush->stages) {
    if (st.kind == StageKind::Reduce)
      reduceStages.append(&st);
  }
  for (const auto *st : reduceStages) {
    emitReduceStage(*st, lowerName);
  }

  // Primary stage: a vertex kernel (walks the node's verts) or — for face
  // brushes like poly-group paint — a face kernel (walks the node's faces).
  if (!vertexStage && !faceStage) {
    err("brush has no vertex or face stage");
    return;
  }
  if (faceStage && !vertexStage) {
    emitFaceKernel(lowerName);
  } else {
    if (vertexStage->params.size() < 1) {
      err("vertex stage must take at least one parameter (the Vertex bundle)");
    }

    if (usesNbr) {
      write("template <CommandTypes TYPES, sculptcore::brush::NbrSource NbrSrc, "
            "sculptcore::brush::AccumMode AccMode>\n");
    } else {
      write("template <CommandTypes TYPES, sculptcore::brush::AccumMode AccMode>\n");
    }
    write("static void ");
    write(lowerName);
    write("(CommandCtx<TYPES> &ctx)\n");
    write("{\n");
    write("  using namespace sculptcore::spatial;\n");
    write("  using namespace litestl::math;\n");
    write("  bool any_moved = false;\n");
    emitTexCtxLocal();

    // Bound attribute handles (resolved per-dab in the executor). A handle is
    // null only for an optional layer that was absent; write kernels declare
    // their target attr so it's always present here.
    for (const auto &f : brush->fields) {
      if (f.kind != FieldKind::Attr)
        continue;
      if (f.domain != AttrDomain::Vertex)
        continue; // vertex stage: vertex attrs
      write("  auto *__attr_");
      write(f.name);
      write(" = ctx.template boundAttr<");
      write(attrCppType(f.type));
      write(">(\"");
      write(f.name);
      write("\"); (void)__attr_");
      write(f.name);
      write(";\n");
    }

    // Non-Vertex vertex params get declared as locals and seeded by the
    // matching reduce-stage output (matched by param name). The vertex
    // body then sees them as ordinary stage params — struct, scalar,
    // or vector. Struct locals are default-constructed; scalars stay
    // uninitialized until the reduce call runs (the executor always
    // calls every reduce stage before the per-vertex loop).
    for (int pi = 1; pi < (int)vertexStage->params.size(); pi++) {
      const auto &p = vertexStage->params[pi];
      write("  ");
      emitTypeRef(p.type, p.structName);
      write(" ");
      write(p.name);
      write(";\n");
    }
    // Call each reduce stage in source order. Argument matching is
    // by-name to a vertex-stage local declared above; both struct
    // and scalar params are passed by reference at the C++ level
    // (the reduce signature already declares scalars as `T &` for
    // out/inout, by value for in — the call site looks the same).
    for (const auto *st : reduceStages) {
      write("  ");
      write(lowerName);
      write(capitalize(st->name));
      write("<TYPES>(ctx");
      for (const auto &rp : st->params) {
        write(", ");
        bool found = false;
        for (int pi = 1; pi < (int)vertexStage->params.size(); pi++) {
          const auto &vp = vertexStage->params[pi];
          if (vp.type != rp.type)
            continue;
          if (!string(vp.name).operator==(string(rp.name.c_str())))
            continue;
          if (rp.type == TypeKind::Struct &&
              !string(vp.structName).operator==(string(rp.structName.c_str())))
            continue;
          write(vp.name);
          found = true;
          break;
        }
        if (!found) {
          errf("reduce param '%s' has no matching vertex-stage local of the same type",
               rp.name.c_str());
          write("/*unmatched*/");
        }
      }
      write(");\n");
    }

    write("  for (auto &");
    write(vertexParamName);
    write(" : ctx.template vertexIter<AccMode>(ctx.node)) {\n");
    indent = 2;
    currentStage = vertexStage;

    // user body
    if (vertexStage->body && vertexStage->body->kind == StmtKind::Block) {
      int savedLocals = (int)locals.size();
      for (const auto &c : vertexStage->body->stmts)
        emitStmt(*c);
      while ((int)locals.size() > savedLocals)
        locals.pop_back();
    }

    // post-iteration side effects: ran only when body did not continue/return.
    writeIndent();
    write("ctx.node.affected_verts.append(");
    write(vertexParamName);
    write(".v);\n");
    writeIndent();
    write("any_moved = true;\n");

    currentStage = nullptr;
    indent = 0;
    write("  }\n");
    write("  if (any_moved) {\n");
    if (kernelWritesGeomOnly()) {
      write("    ctx.node.update(Spatial_UpdateNormals | Spatial_UpdateGPUGeom | "
            "Spatial_RegenBounds);\n");
    } else {
      write("    ctx.node.update(Spatial_UpdateNormals | Spatial_UpdateGPU | "
            "Spatial_RegenBounds);\n");
    }
    write("  }\n");
    write("}\n\n");
  } // end vertex/face primary-kernel branch

  // post-stage: empty for Wave 1.
  write("template <CommandTypes TYPES>\n");
  write("static void ");
  write(lowerName);
  write("Post(CommandCtxBase &ctx, std::span<typename TYPES::node_type *> nodes)\n");
  write("{\n");
  write("  (void)ctx; (void)nodes;\n");
  write("}\n\n");

  // wire-up function: identical shape to existing createDrawBrush. For
  // for_neighbor brushes it carries the NbrSource policy (default: live disk
  // walk) through to the kernel instantiation assigned to def.exec.
  if (usesNbr) {
    write("template <CommandTypes TYPES, sculptcore::brush::NbrSource NbrSrc = "
          "sculptcore::brush::LiveDiskNbr, "
          "sculptcore::brush::AccumMode AccMode = sculptcore::brush::AccumLive>\n");
  } else {
    write("template <CommandTypes TYPES, "
          "sculptcore::brush::AccumMode AccMode = sculptcore::brush::AccumLive>\n");
  }
  write("static void create");
  write(camelName);
  write("Brush(BrushCommandDef<CommandCtx<TYPES>> &def)\n");
  write("{\n");
  // Host stages, if any, are composed into a single lambda so multiple
  // hosts on one brush still flow through one execHost slot.
  if (hostStages.size() > 0) {
    write("  def.execHost = [](CommandCtxBase &ctx, Brush &brush) {\n");
    for (const auto *st : hostStages) {
      write("    ");
      write(lowerName);
      write(capitalize(st->name));
      write("<TYPES>(ctx, brush);\n");
    }
    write("  };\n");
  }
  write("  def.execPre  = ");
  write(lowerName);
  write("Pre<TYPES>;\n");
  write("  def.exec     = ");
  write(lowerName);
  if (usesNbr)
    write("<TYPES, NbrSrc, AccMode>;\n");
  else
    write("<TYPES, AccMode>;\n");
  write("  def.execPost = ");
  write(lowerName);
  write("Post<TYPES>;\n");
  PreparedPreludeProof preludeProof(*brush);
  bool hostsNoop = true;
  for (const auto *stage : hostStages)
    hostsNoop &= preludeProof.host(*stage);
  write("  def.preparedHostNoop = ");
  write(hostsNoop ? "true;\n" : "false;\n");
  write("  def.preparedScalarSafe = ");
  int vertexSaves = 0, faceSaves = 0, customSaves = 0;
  for (const auto &save : brush->saves) {
    vertexSaves += save.domain == AttrDomain::Vertex;
    faceSaves += save.domain == AttrDomain::Face;
    customSaves += save.name != string("co") && save.name != string("no") &&
                   save.name != string("mask") && save.name != string("color");
  }
  write(!preparedStateUnsafe && hostsNoop && (bool(vertexStage) != bool(faceStage)) &&
                vertexSaves <= 8 && faceSaves <= 8 && customSaves <= 10 &&
                preludeProof.reduceCalls(vertexStage ? vertexStage : faceStage)
            ? "true;\n"
            : "false;\n");
  // for_neighbor reads ctx.co_prev — tell the executor to snapshot it.
  if (neighborLoopUsed) {
    write("  def.needsCoPrev = true;\n");
  }
  // Non-accumulate eligibility (see plans/nonAccumMode.md): accumulable is the
  // default; the executor runs the AccumOrig instantiation when non-accumulate
  // mode is on for the stroke. @paint writes attributes and @unbounded fields
  // are anchored, so from-base re-derivation is meaningless for both; an
  // @incremental kernel is driven by a per-dab delta, so it has no base; a
  // grad() kernel differentiates over v.co, which the base-read proxy breaks.
  write("  def.accumulable = ");
  write((!brush->isPaint && !brush->isUnbounded && !brush->isIncremental &&
         !brushUsesGrad())
            ? "true"
            : "false");
  write(";\n");
  // `@relaxation`: relaxes the surface rather than displacing it, so it stays
  // on AccumLive and never accumulates into `.brush.disp.vec`.
  if (brush->isRelaxation) {
    write("  def.relaxesBase = true;\n");
  }
  // `@grabmode`: eligible for the from-orig grab policy. The executor decides
  // whether the stroke actually uses it (CommandExecutor::anchoredGrab).
  if (brush->isGrabMode) {
    write("  def.grabModeCapable = true;\n");
  }
  // `@unbounded`: the field is live out to radius * unboundedExtent, which the
  // executor uses as the node-filter floor so no leaf seam falls inside it.
  if (brush->isUnbounded) {
    write("  def.unbounded = true;\n");
  }
  // `@incremental`: the host must feed the per-dab delta this kernel expects
  // (accumulable is already false above — this says *why*, which is what the
  // host needs to shape the dab).
  if (brush->isIncremental) {
    write("  def.incremental = true;\n");
  }
  // `@planeFrame`: the executor may substitute the dab's surfacePos/surfaceNo
  // with the stroke's plane-frame policy (brush/plane_frame.h).
  if (brush->usesPlaneFrame) {
    write("  def.usesPlaneFrame = true;\n");
  }
  // A `face` stage means the kernel is dispatched per-face, not per-vertex.
  if (brushHasFaceStage(*brush)) {
    write("  def.faceMode = true;\n");
  }
  // `v.mask` is a builtin Vertex field, so unlike a painted attr it leaves no
  // trace in def.attrs — scan the bodies for the write instead.
  if (brushWritesMember(*brush, "mask")) {
    write("  def.writesMask = true;\n");
  }
  // Declared attribute layers — resolved + bound per dab by the executor.
  // `materialize` is unconditionally true (a read-only handle still needs
  // storage); `kernelWrites` is inferred from the stage bodies, because that
  // is the bit that decides whether a write needs a destination.
  for (const auto &f : brush->fields) {
    if (f.kind != FieldKind::Attr)
      continue;
    MemberWriteKind wk = brushScanMemberWrites(*brush, f.name.c_str());
    if (wk == MemberWriteKind::Nested) {
      errf("write through a swizzle or index of attr '%s' is not supported "
           "(assign the whole attr instead)",
           f.name.c_str());
    }
    write("  def.attrs.append(sculptcore::brush::BrushAttrManifestEntry{\"");
    write(f.name);
    write("\", \"");
    write(f.boundName);
    write("\", ");
    write(attrTypeEnum(f.type));
    write(", ");
    write(attrDomainEnum(f.domain));
    write(", true, ");
    write(wk == MemberWriteKind::TopLevel ? "true" : "false");
    write(", ");
    write(attrUseEnum(f.use));
    write("});\n");
    // Independent cross-check: every body-written attr should be in the
    // `save` list (else its stroke does not undo) and nothing else should be
    // (dead capture). A warning, not an error — a host-pre-pass-written attr
    // that needs capture would be a legitimate exception.
    bool saved = false;
    for (const auto &s : brush->saves) {
      if (s.name.operator==(f.name)) {
        saved = true;
        break;
      }
    }
    if (wk == MemberWriteKind::TopLevel && !saved) {
      warnf("attr '%s' is written but not in the save list — its stroke will "
            "not undo",
            f.name.c_str());
    } else if (wk == MemberWriteKind::None && saved) {
      warnf("attr '%s' is in the save list but never written — dead capture",
            f.name.c_str());
    }
  }
  for (const auto &f : brush->fields) {
    if (f.kind != FieldKind::Uniform) {
      continue;
    }
    write("  def.uniforms.append(sculptcore::brush::BrushUniformManifestEntry{\"");
    write(f.name);
    write("\", ");
    write(f.type == TypeKind::Float ? "true" : "false");
    write(", ");
    write(fieldDynamicCapable(f) ? "true" : "false");
    write(", ");
    write(doubleLit(f.hasDefault ? f.defaultValue : 0.0));
    write(", ");
    write(f.hasRange ? "true" : "false");
    write(", ");
    write(doubleLit(f.hasRange ? f.rangeMin : 0.0));
    write(", ");
    write(doubleLit(f.hasRange ? f.rangeMax : 0.0));
    write(", ");
    if (extrasMode && fieldUsesStore(f)) {
      write("kExtraSlot_");
      write(f.name);
    } else {
      write("-1");
    }
    write(", sculptcore::props::Prop::");
    write(f.type == TypeKind::Float  ? "FLOAT32"
          : f.type == TypeKind::Int  ? "INT32"
          : f.type == TypeKind::Bool ? "BOOL"
                                     : "INVALID_TYPE");
    write(", ");
    write(f.hasDefault ? "true" : "false");
    write("});\n");
  }
  write("  def.loadUniformProps = [](sculptcore::brush::Brush &brush, "
        "sculptcore::props::DeviceInputCtx *ctx) {\n");
  for (const auto &f : brush->fields) {
    if (f.kind != FieldKind::Uniform || !fieldDynamicCapable(f))
      continue;
    double def = f.hasDefault ? f.defaultValue : 0.0;
    if (extrasMode && fieldUsesStore(f)) {
      // Evaluated values must not replace the authored base.
      write("    brush.setEvaluatedNamed");
      write(storeSuffix(f.type));
      write("(kExtraSlot_");
      write(f.name);
      write(", brush.props.lookupValue<");
      write(scalarCppType(f.type));
      write(">(\"");
      write(f.name);
      write("\", ");
      write(f.type == TypeKind::Bool  ? string(def != 0 ? "true" : "false")
            : f.type == TypeKind::Int ? integralLiteral(def)
                                      : floatLit(def));
      write(", ctx));\n");
      continue;
    }
    write("    brush.");
    write(f.name);
    write(" = brush.props.lookupValue<");
    write(f.type == TypeKind::Bool  ? "bool"
          : f.type == TypeKind::Int ? "int"
                                    : "float");
    write(">(\"");
    write(f.name);
    write("\", ");
    if (f.type == TypeKind::Bool) {
      write(def != 0 ? "true" : "false");
    } else if (f.type == TypeKind::Int) {
      char literal[32];
      std::snprintf(literal, sizeof(literal), "%.0f", def);
      write(literal);
    } else {
      write(floatLit(def));
    }
    write(", ctx);\n");
  }
  write("  };\n");
  write("}\n\n");

  emitGpuPack(camelName);

  write("} // namespace sculptcore::brush::command\n");
}

} // namespace sculptcore::brush::sbrush::cpp_emit
