# Auto-generated by LSTL_GeneratePython — do not edit.
from ._prim import int32
from ._runtime import BoundObject
from enum import IntEnum

class DynTopoMode(IntEnum):
    Subdivide = 0
    Collapse = 1
    Both = 2

class DynTopoRegion(IntEnum):
    Sphere = 0
    GradedRecursive = 1

class DynTopoParams(BoundObject):
    l_max: float
    l_min: float
    mode: DynTopoMode
    grade: float
    region: DynTopoRegion
    graded_generation_scale: float
    graded_len_sq_factor: float
    graded_max_hops: int32
    graded_valence_relief: int32
    max_rounds: int32
    do_flips: bool
    max_splits: int32
    max_collapses: int32
    do_smooth: bool
    smooth_lambda: float
    reproject_uvs: bool
    preserve_features: bool

class DynTopoStats(BoundObject):
    splits: int32
    collapses: int32
    flips: int32
    smooths: int32
    rounds: int32
    capped: bool
    budget_hit: bool
    graded_hops: int32
