set( CMAKE_CXX_COMPILER clang )
set( CMAKE_C_COMPILER clang )
set( CMAKE_C_FLAGS " -DWIN32 ")

set( CMAKE_C_FLAGS_RELEASE " -DNDEBUG -DWIN32 -O3")
set( CMAKE_C_FLAGS_RELWITHDEBINFO " -DNDEBUG -DWIN32 -g -O2 ")
set( CMAKE_C_FLAGS_DEBUG " -DWIN32 -g -O0 ")

set( CMAKE_CXX_FLAGS " -DWIN32 ")

set( CMAKE_CXX_FLAGS_RELEASE " -DNDEBUG -DWIN32 -O3 ")
set( CMAKE_CXX_FLAGS_RELWITHDEBINFO " -DNDEBUG -DWIN32 -g -O2 ")
set( CMAKE_CXX_FLAGS_DEBUG " -DWIN32 -g -O0 ")
