#pragma once
#include "../props/prop_curve.h"
#include "../props/prop_dynamics.h"
#include "../props/prop_struct.h"
#include "litestl/binding/binding.h"
#include "litestl/math/vector.h"
#include "litestl/util/compiler_util.h"

#include <array>
#include <cmath>

#include "props.h"

namespace sculptcore::brush {
using litestl::util::StrLiteral;
using litestl::math::float3;

// Falloff curve shapes selectable per brush. The three analytic kinds
// inline a closed form; `Curve` reads `Brush::falloff_curve` as a
// 256-entry LUT with linear interpolation. `t` is the normalized 0..1
// centerwise input — 1 at the brush center, 0 at the radius. Smoothstep
// is the historical default and keeps regression dumps bit-identical
// when no `set_falloff` runs.
enum class FalloffKind : unsigned char {
  Smoothstep = 0,
  Linear = 1,
  Gaussian = 2,
  Curve = 3,
};

// Spatial metric mapping a vertex offset from the brush center to the
// normalized 0..1 distance fed into the falloff curve. This is the DSL
// plan's `Falloff` tagged-union discriminant, orthogonal to the curve
// shape (`FalloffKind`):
//   Spherical — euclidean radius (historical default, bit-identical).
//   Cube      — max(|dx|,|dy|,|dz|), the legacy SQUARE-brush metric.
//   Linear    — distance projected onto `falloff_dir` (stroke-line falloff).
enum class FalloffShape : unsigned char {
  Spherical = 0,
  Cube = 1,
  Linear = 2,
};

inline constexpr int kFalloffCurveSize = 256;

struct Brush {
  props::StructProp props;
  props::DeviceInputCtx deviceInputCtx;

  float strength = 1;
  float radius = 1;
  /* Fraction of `radius` between successive brush dabs along a stroke. */
  float spacing = 0.25f;
  bool invert = false;
  FalloffKind falloff_kind = FalloffKind::Smoothstep;
  FalloffShape falloff_shape = FalloffShape::Spherical;
  // Direction for `FalloffShape::Linear` (expected normalized). Unused by
  // the other shapes. Default +Z keeps the value well-defined.
  float3 falloff_dir{0, 0, 1};

  // Kelvinlet brush uniforms — Lamé-style material constants. Live on Brush
  // (rather than only on CommandCtx) because they're authored alongside
  // strength/radius. Defaults match the kelvinlet paper's "soft rubber".
  float mu = 1.0f;
  float nu = 0.4f;

  // Grab-style ctx state (kelvinlet, future pose). `grabFrom` is the stroke
  // origin captured at the start of the dab; `grabTo` is the current cursor.
  float3 grabFrom{0, 0, 0};
  float3 grabTo{0, 0, 0};

  // Pose-brush cage. `poseCageRest` is sampled when the dab starts; the DSL
  // displaces each vertex by a weighted sum of `poseCageNow[i] - poseCageRest[i]`
  // with weights = 1 / (1 + |v.co - poseCageRest[i]|²). Four anchors is the
  // tightest fit that still gives a smooth pose without needing a loop in
  // the DSL (Wave 4b has no `for`).
  float3 poseCageRest[4] = {};
  float3 poseCageNow[4] = {};

  // Authoring source of truth for the `Curve` falloff. Defaults to a
  // smoothstep so a brush switched to `Curve` without ever calling
  // `setFalloffCurvePreset` still produces the historical falloff shape.
  props::detail::curve::CurveGen falloffCurve{props::PropCurves::SMOOTHSTEP};

  // Baked output of `falloffCurve`, consulted when
  // `falloff_kind == FalloffKind::Curve`. Regenerated by `rebakeFalloff()`.
  std::array<float, kFalloffCurveSize> falloff_curve = [] {
    props::detail::curve::CurveGenSimple<props::PropCurves::SMOOTHSTEP> ss;
    return props::detail::curve::bake_curve_lut<kFalloffCurveSize>(ss);
  }();

  static litestl::binding::types::Struct<Brush> *defineBindings()
  {
    using namespace litestl::binding;
    types::Struct<Brush> *st =
        new types::Struct<Brush>("sculptcore::brush::Brush", sizeof(Brush));

    BIND_STRUCT_DEFAULT_CONSTRUCTOR(st);

    BIND_STRUCT_MEMBER(st, strength);
    BIND_STRUCT_MEMBER(st, radius);
    BIND_STRUCT_MEMBER(st, spacing);
    BIND_STRUCT_MEMBER(st, invert);
    BIND_STRUCT_MEMBER(st, mu);
    BIND_STRUCT_MEMBER(st, nu);
    BIND_STRUCT_MEMBER(st, grabFrom);
    BIND_STRUCT_MEMBER(st, grabTo);
    BIND_STRUCT_MEMBER(st, props);
    BIND_STRUCT_METHOD(st, loadProps, MARGS());
    BIND_STRUCT_METHOD(st, writeProps, MARGS());

    return st;
  }

  Brush() : props(&structDef_)
  {
    structDef_.Float32("strength", "strength");
    structDef_.Float32("radius", "radius");
    structDef_.Float32("spacing", "spacing");
    structDef_.Bool("invert", "invert");
    structDef_.Float32("mu", "mu");
    structDef_.Float32("nu", "nu");
  }

  void loadProps()
  {
    strength = props.lookupValue<float>("strength", 1.0);
    radius = props.lookupValue<float>("radius", 1.0);
    spacing = props.lookupValue<float>("spacing", 0.25);
    invert = props.lookupValue<bool>("invert", false);
    mu = props.lookupValue<float>("mu", 1.0);
    nu = props.lookupValue<float>("nu", 0.4);
  }

  void writeProps()
  {
    props.setValue<float>("strength", strength);
    props.setValue<float>("radius", radius);
    props.setValue<float>("spacing", spacing);
    props.setValue<bool>("invert", invert);
    props.setValue<float>("mu", mu);
    props.setValue<float>("nu", nu);
  }

  // Normalized 0..1+ distance from the brush center for a vertex offset
  // `delta = co - surfacePos`, per the active `falloff_shape`. Feeds the
  // curve via `t = 1 - min(dist, 1)`. WGSL mirrors this in
  // `brush_falloff_dist`; changing one without the other breaks the
  // CPU/GPU bit-equality contract.
  float falloffDist(float3 delta) const
  {
    float inv_r = 1.0f / radius;
    switch (falloff_shape) {
    case FalloffShape::Spherical:
      return delta.length() * inv_r;
    case FalloffShape::Cube: {
      float ax = std::fabs(delta[0]);
      float ay = std::fabs(delta[1]);
      float az = std::fabs(delta[2]);
      float m = ax > ay ? ax : ay;
      m = m > az ? m : az;
      return m * inv_r;
    }
    case FalloffShape::Linear:
      return std::fabs(delta.dot(falloff_dir)) * inv_r;
    }
    return delta.length() * inv_r;
  }

  // Evaluate the active falloff curve at normalized centerwise `t`
  // (1 at center, 0 at radius). Source of truth for the C++ side; the
  // WGSL emitter mirrors the same branches in `brush_falloff`.
  // The Gaussian width (9 in the exponent) hits exp(-9) ~= 1.2e-4 at
  // the edge, so no hard cutoff is needed. The Curve branch does
  // clamped linear interpolation over `falloff_curve` — N-1 segments,
  // index N-1 read directly when t lands exactly at 1.
  float falloffEval(float t) const
  {
    switch (falloff_kind) {
    case FalloffKind::Smoothstep:
      return t * t * (3.0f - 2.0f * t);
    case FalloffKind::Linear:
      return t;
    case FalloffKind::Gaussian: {
      float u = 1.0f - t;
      return std::exp(-9.0f * u * u);
    }
    case FalloffKind::Curve: {
      float clamped = t < 0.0f ? 0.0f : (t > 1.0f ? 1.0f : t);
      float scaled = clamped * (float)(kFalloffCurveSize - 1);
      int i0 = (int)scaled;
      if (i0 >= kFalloffCurveSize - 1) return falloff_curve[kFalloffCurveSize - 1];
      float frac = scaled - (float)i0;
      return falloff_curve[i0] * (1.0f - frac) + falloff_curve[i0 + 1] * frac;
    }
    }
    return t;
  }

  // Overwrite `falloff_curve` with a named preset. `inverse` flips the
  // smoothstep shape (full strength at the edge, zero at the center) —
  // useful for verifying the LUT actually drives the kernel rather
  // than being shadowed by the analytic dispatch.
  enum class CurvePreset { Smoothstep, Linear, Inverse, Gaussian };

  // Re-sample `falloffCurve` (the authoring curve) into `falloff_curve`
  // (the baked LUT). Call after mutating `falloffCurve`.
  void rebakeFalloff()
  {
    props::detail::curve::bake_curve_lut(
        *falloffCurve.gen, falloff_curve.data(), kFalloffCurveSize);
  }

  // Construct the authoring `CurveGen` for a named preset, then rebake.
  // Inverse maps to a reverse-linear b-spline (1-t); Gaussian maps to a
  // centered-bump `CurveGenGuassian` parameterized to match the brush's
  // analytic edge gaussian exp(-9(1-t)^2) (offset=1, 1/(2σ²)=9).
  void setFalloffCurvePreset(CurvePreset p)
  {
    using namespace props::detail::curve;

    switch (p) {
    case CurvePreset::Smoothstep:
      falloffCurve = CurveGen(props::PropCurves::SMOOTHSTEP);
      break;
    case CurvePreset::Linear:
      falloffCurve = CurveGen(props::PropCurves::LINEAR);
      break;
    case CurvePreset::Inverse: {
      falloffCurve = CurveGen(props::PropCurves::BSPLINE);
      static_cast<CurveGenBSpline *>(falloffCurve.gen)
          ->loadTemplate(SplineTemplate::REVERSE_LINEAR);
      break;
    }
    case CurvePreset::Gaussian: {
      falloffCurve = CurveGen(props::PropCurves::GUASSIAN);
      CurveGenGuassian *g = static_cast<CurveGenGuassian *>(falloffCurve.gen);
      g->height = 1.0;
      g->offset = 1.0;
      g->deviation = 1.0 / std::sqrt(18.0);
      break;
    }
    }

    rebakeFalloff();
  }

private:
  props::StructDef structDef_;
};
} // namespace sculptcore::brush
