#include "spatial_shaders.h"
#include "gpu/shader.h"
#include "gpu/uniform_link.h"
#include "litestl/binding/binding.h"

/* WGSL source text — generated from basic_line.wgsl / basic_mesh.wgsl by
 * tools/wgsl-to-spirv.mjs. Available on all targets (native + WASM). */
#include "basic_line.wgsl.h"
#include "basic_mesh.wgsl.h"

#ifndef WASM
/* SPIR-V byte arrays — generated by the same tool; native-only because
 * WASM doesn't carry a Vulkan backend. */
#  include "basic_line.spirv.h"
#  include "basic_mesh.spirv.h"
#endif

namespace sculptcore::spatial {

litestl::binding::types::Struct<SpatialShaders> *SpatialShaders::defineBindings()
{
  using namespace litestl::binding;

  types::Struct<SpatialShaders> *st = new types::Struct<SpatialShaders>(
      "sculptcore::spatial::SpatialShaders", sizeof(SpatialShaders));

  BIND_STRUCT_MEMBER(st, basicMeshShader);
  BIND_STRUCT_MEMBER(st, basicLineShader);

  return st;
}

namespace {

/* Build the single "DefaultBlock" UBO descriptor that the spatial shaders
 * read. Currently both shaders bind to the same logical UBO at (set=0,
 * binding=0) in their WGSL; the link pass would normally stamp those slots
 * but we hard-code them here while the link pass is still in flight. */
static gpu::UniformBlockDef *makeDefaultBlock(bool withNormalMatrix)
{
  using namespace litestl::math;
  using litestl::alloc::New;

  litestl::util::Vector<gpu::UniformDefBase *> fields;
  fields.append(New<gpu::UniformDef<mat4>>(
      "UniformDef", "drawMatrix", gpu::GPUType::FLOAT32, 16, mat4().identity()));
  if (withNormalMatrix) {
    fields.append(New<gpu::UniformDef<mat4>>(
        "UniformDef", "normalMatrix", gpu::GPUType::FLOAT32, 16, mat4().identity()));
  }
  fields.append(New<gpu::UniformDef<float4>>(
      "UniformDef", "uColor", gpu::GPUType::FLOAT32, 4,
      float4(1.0f, 1.0f, 1.0f, 1.0f)));

  auto *block = New<gpu::UniformBlockDef>("UniformBlockDef",
                                          litestl::util::string("DefaultBlock"),
                                          std::move(fields));
  block->set = 0;
  block->binding = 0;
  return block;
}

gpu::ShaderDef makeBasicLineShader()
{
  using namespace litestl::math;
  /* These ShaderDefs are static-storage globals that outlive every test's
   * test_end()/print_blocks() call. Mark their bootstrap allocations as
   * expected-permanent so they don't show up as leaks. */
  litestl::alloc::PermanentGuard permGuard;
  gpu::ShaderDef def("Basic Line Shader",
                     shaders::generated::basic_line_wgsl,
                     {
                         {"position", gpu::GPUType::FLOAT32, 3},
                         {"color", gpu::GPUType::FLOAT32, 4},
                     },
                     {makeDefaultBlock(/*withNormalMatrix=*/false)},
                     {});
#ifndef WASM
  def.spirv = shaders::generated::basic_line_spirv;
  def.spirvSize = sizeof(shaders::generated::basic_line_spirv) / sizeof(uint32_t);
#endif
  gpu::linkShaderDef(&def);
  return def;
}

gpu::ShaderDef makeBasicMeshShader()
{
  using namespace litestl::math;
  litestl::alloc::PermanentGuard permGuard;
  gpu::ShaderDef def("Basic Mesh Shader",
                     shaders::generated::basic_mesh_wgsl,
                     {
                         {"position", gpu::GPUType::FLOAT32, 3},
                         {"normal", gpu::GPUType::FLOAT32, 3},
                     },
                     {makeDefaultBlock(/*withNormalMatrix=*/true)},
                     {});
#ifndef WASM
  def.spirv = shaders::generated::basic_mesh_spirv;
  def.spirvSize = sizeof(shaders::generated::basic_mesh_spirv) / sizeof(uint32_t);
#endif
  gpu::linkShaderDef(&def);
  return def;
}

} // namespace

SpatialShaders spatialShaders = {makeBasicMeshShader(), makeBasicLineShader()};
} // namespace sculptcore::spatial
