import * as binding from '@litestl/typescript-runtime'
import {execSync} from 'child_process'
import fs from 'fs'
import os from 'os'
import Path from 'path'
import * as prettier from '@pathtx/prettier'

/** Files/folders in typescript/ to not delete when rebuilding. */
const staticFiles = new Set(['package.json', 'readme.md', 'tsconfig.json', 'api', 'node_modules', 'build'])

const wasmURL = process.argv[2] ?? '../build/sculptcore.js'
const _wasm = await import(wasmURL)
const wasmMod = await _wasm.default({wasmMemory: binding.createWasmMemory()})

function setupWasm(wasm: any) {
  for (const k in wasm) {
    if (typeof k === 'string' && k[0] == '_') {
      wasm[k.slice(1)] = wasm[k]
    }
  }

  const wasm2 = binding.createWasmHelpers(wasm, _wasm)
  return wasm2 as unknown as binding.INeededWasm
}

const wasm = setupWasm(wasmMod)

wasmMod._initBindings()
const managerPtr = wasmMod._getBindingManager()
const manager = new binding.BindingManager(wasm, managerPtr)
manager.load()
const files = manager.generateTypeScript()

const baseDir = Path.resolve('../typescript')
const header =
  `
/* Warning: auto-generated file! Regenerate with 'pnpm build' in 'tools/' folder. */
`.trim() + '\n'
const footer = ''

// Files generated by another tool (`make.mjs codegen`) that live inside the
// regenerated tree — stashed across the wipe and restored below.
const preservePaths = ['sculptcore/brush/brushWgsl.ts']
const preserved = new Map<string, Buffer>()
for (const rel of preservePaths) {
  const p = Path.join(baseDir, rel)
  if (fs.existsSync(p)) {
    preserved.set(rel, fs.readFileSync(p))
  }
}

for (const entry of fs.readdirSync(baseDir)) {
  if (staticFiles.has(entry.toLowerCase())) {
    continue
  }
  fs.rmSync(Path.join(baseDir, entry), {recursive: true, force: true})
}

function gitConfig(key: string): string {
  try {
    return execSync(`git config --get ${key}`, {
      cwd     : baseDir,
      encoding: 'utf8',
      stdio   : ['ignore', 'pipe', 'ignore'],
    }).trim()
  } catch {
    // unset (exit 1) or git unavailable
    return ''
  }
}

function getNativeEOL(): '\n' | '\r\n' {
  // core.eol pins the working-tree ending outright and wins over core.autocrlf.
  const coreEol = gitConfig('core.eol')
  if (coreEol === 'lf') {
    return '\n'
  }
  if (coreEol === 'crlf') {
    return '\r\n'
  }

  const autocrlf = gitConfig('core.autocrlf')
  if (autocrlf === 'input' || autocrlf === 'false') {
    return '\n'
  }
  // 'true', or unset with core.eol=native → OS-native EOL
  return os.EOL === '\r\n' ? '\r\n' : '\n'
}

const eol = getNativeEOL()

function toEOL(text: string): string {
  return text.replace(/\r\n?|\n/g, eol)
}

for (const [rel, content] of preserved) {
  const p = Path.join(baseDir, rel)
  fs.mkdirSync(Path.dirname(p), {recursive: true})
  fs.writeFileSync(p, toEOL(content.toString('utf8')))
}
const prettierConfig = (await prettier.resolveConfig(baseDir)) ?? {}

for (const [path, file] of files) {
  const dirname = Path.join(baseDir, Path.dirname(path))
  fs.mkdirSync(dirname, {recursive: true})
  const finalPath = Path.join(baseDir, path)
  const raw = header + file + footer
  let formatted: string
  try {
    formatted = await prettier.format(raw, {
      ...prettierConfig,
      parser   : 'typescript',
      filepath : finalPath,
      endOfLine: eol === '\r\n' ? 'crlf' : 'lf',
    })
  } catch (err) {
    console.warn(`prettier failed for ${path}: ${(err as Error).message.split('\n')[0]} — writing unformatted`)
    formatted = raw
  }
  fs.writeFileSync(finalPath, toEOL(formatted))
}
//@ts-ignore
import {termColor} from '../source/litestl/tests/termColor.js'
console.log(termColor('Generated typescript interfaces', 'blue'))
