add_subdirectory(litestl)
add_subdirectory(mesh)
add_subdirectory(spatial)
add_subdirectory(wasm)
add_subdirectory(props)
add_subdirectory(brush)
add_subdirectory(core)
add_subdirectory(gpu)
add_subdirectory(meshlog)
if (NOT BUILD_WASM)
  add_subdirectory(window)
  add_subdirectory(opengl)
  add_subdirectory(app)
  add_subdirectory(debug)
endif()
