add_subdirectory(litestl)
add_subdirectory(mesh)
add_subdirectory(spatial)
add_subdirectory(wasm)
if (NOT BUILD_WASM)
#	add_subdirectory(io)
#	add_subdirectory(gpu)
#	add_subdirectory(window)
endif()
add_subdirectory(props)
add_subdirectory(brush)
add_subdirectory(core)
if (NOT BUILD_WASM)
#	add_subdirectory(app)
endif()

